language: CSharp
mono:
  - latest
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm install latest
  - dnu restore
script:
  - pushd Nilgiri.Tests && dnx test -parallel none; popd
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: build/publish
  on:
    branch: master
notifications:
  email: false
