language: CSharp
mono:
  - latest
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm install 1.0.0-beta6 -r mono
  - dnu restore
script:
  - dnx . test -parallel none
notifications:
  email: false
